[package]
name = "onebrc"
version = "0.1.0"
edition = "2021"

[dependencies]
rustc-hash = "2.1.1"
memmap2 = "0.9.9"
libc = "0.2.178"

[profile.bench]
debug = true
lto = "fat"

[profile.release]
debug = true
strip = "none"
panic = "abort"
lto = "fat"
codegen-units = 1
