[package]
name = "onebrc"
version = "0.1.0"
edition = "2021"

[dependencies]
rustc-hash = "2.1.1"
memmap2 = "0.9.9"

[profile.bench]
debug = true
lto = "fat"

[profile.release]
debug = false
panic = "abort"
lto = "fat"
